dataset:
  data_dir: "inputs/crop_part1"
  batch_size: 32
  image_size: [224, 224]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

training:
  num_epochs: 50
  accumulation_steps: 2
  learning_rate: 0.001
  weight_decay: 1e-4
  scheduler_factor: 0.1
  scheduler_patience: 5
  early_stopping_patience: 10
  accuracy_threshold: 5
  weight_dir: "pipeline/weights"
  model_name: "AgeEfficientNet"
  log_dir: "runs"
  checkpoint_dir: "checkpoint"

paths:
  cascade_path: "pipeline/video_image/haarcascade_frontalface_default.xml"

output:
  output_dir: "outputs"
